### ISSUE TITLE
Error while trying to open player.dat file

### ISSUE THREAD

**Issue by Foorack** [Deanveloper/nbtnav#1]
Compiled master as of commit https://github.com/Deanveloper/nbtnav/commit/3b8b53390f4b7a62719addc718f302b71ea0eb45 

Trying to open a playerfile with `nbtnav <uuid>.dat` returns with

> Error: Expected compound at top level.

**Comment by Deanveloper** [comment]
Sorry, this is an unfinished project that I guess I left in the dust. I'll resume work, also mark it as unfinished in the README

**Comment by Foorack** [comment]
Oh, okay, I didn't know it wasn't finished. When searching for "bash nbt" on google your project was the first one which came up. If you want to finish it is obviously completely up to, as there seem to be other nbtviewers as well, but looks like a cool project. Either way it would be good to add into the README saying something like "still under construction!" for other googles who come the same way as I did. :slightly_smiling_face:

**Comment by Deanveloper** [comment]
It should mostly work for viewing, haven't gotten to get saving working yet. I'm going to resolve this for now and update the readme :)
